# Generated by Django 4.2.7 on 2023-12-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroboard',
            name='variant',
            field=models.CharField(choices=[('GoodBad', 'Good - Bad')], max_length=250),
        ),
    ]
