# Generated by Django 4.2.7 on 2023-12-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retro', '0003_alter_retroboard_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrospectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_address', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('variant', models.CharField(choices=[('Good / Bad', 'Good / Bad'), ('Good / Bad / Notgoodnotbad', 'Good / Bad / Notgoodnotbad'), ('More / Less', 'More / Less'), ('More / Less / Start / Stop', 'More / Less / Start / Stop')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetroTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.retrospectiveboard')),
            ],
        ),
        migrations.DeleteModel(
            name='RetroBoard',
        ),
    ]
