# Generated by Django 4.2.7 on 2023-12-14 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0004_retrospectiveboard_retroticket_delete_retroboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrospectiveboard',
            name='unique_address',
        ),
        migrations.AddField(
            model_name='retrospectiveboard',
            name='address',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='retrospectiveboard',
            name='variant',
            field=models.CharField(choices=[('Good / Bad', 'Good / Bad'), ('Good / Bad / Not Good Not Bad', 'Good / Bad / Not Good Not Bad'), ('More / Less', 'More / Less'), ('More / Less / Start / Stop', 'More / Less / Start / Stop')], max_length=50),
        ),
        migrations.DeleteModel(
            name='RetroTicket',
        ),
    ]
