# Generated by Django 4.2.7 on 2023-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0006_retroticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroticket',
            name='ticket_type',
            field=models.CharField(max_length=50),
        ),
    ]
