# Generated by Django 4.2.7 on 2023-12-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0007_alter_retroticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectiveboard',
            name='last_retrospective_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_boards', to='retro.retrospectiveboard'),
        ),
    ]
